spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  oauth2:
    client:
      client-id: platform
      clientSecret: 123456
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      egistered-redirect-uri: http://localhost:8080/sysmenu/menulist
    resource:
    userInfoUri: http://localhost:8080/auth/user/me
  servlet:
    multipart:
      location: D:/images/
mybatis-plus:
  configuration:
    cache-enabled: false

